### PR TITLE
Adjust server.py to follow PEP 8 guidelines

### PR DESCRIPTION
**Pull request by Hexadigital**
While [PEP 8](https://www.python.org/dev/peps/pep-0008/) is a series of guidelines, and not necessarily a requirement, there are a lot of automated build tools that enforce it. The reason for this is that PEP 8 provides a clear standard for even more readable code.

There were also a few odd things I cleaned up, like double comments (`#    #  comment here`) and some unnecessary string concatenation, like adding a newline onto the end of a string instead of including it in the string.

(this pull request does not break or change any code, it only makes it more readable)

### CODE REVIEW

**Comment by Frostflake** [comment]
@alundesap Sorry to ping you, but did this get overlooked?

**Comment by alundesap** [comment]
Yes, overlooked.  I don't check this code project often and have been away for a week of work meetings and several days of personal time.  Will check into it now.
-Andrew

**Review by andrewlunde — APPROVED** [review]
I suffer from J2ME WAP HTML coding habits.  <br />
These changes seem fine.

**Review by andrewlunde — APPROVED** [review]
OK

**Review by andrewlunde — APPROVED** [review]
These formatting changes seem fine to me.  -Andrew

**Comment by Frostflake** [comment]
Is there anything I should do or anyone I should alert in order for this to be merged now that it has been approved?

**Review by andrewlunde — APPROVED** [review]
Approved. -Andrew

**Comment by Frostflake** [comment]
Sorry, apparently I had to resign the CLA - you should be able to merge it now.

**Pull request merged**
